title: FaasJ Project
logo: /assets/img/Screenshot 2021-05-31 at 11.59.57.png
description: Pure Java opensource serverless framework
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
